name: deployment-gate
on:
  workflow_dispatch:

jobs:
  change:
    name: Change Request
    runs-on: ubuntu-latest
    steps:     
      - name: ServiceNow DevOps Change Attributes
        uses: ServiceNow/servicenow-devops-change@dev2
        with:
               # ServiceNow Instance URL
                instance-url: ${{ secrets.SN_INSTANCE_URL }}
                  # Devops Integration User Name
                devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
                  # Devops Integration User Password
                devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
                  # Orchestration Tool Id
                tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
                  # Display Name of the Job
                job-name: 'Change Request'
                  # Github Context
                context-github: ${{ toJSON(github) }}
                  # The max. time in seconds to wait until the action should fail.
                timeout: 240 # optional, default is 3600
                  # The time in seconds to wait between trying the API.
                interval: 100 # optional, default is 100
                  # The customized inputs to create change with the requested details.
                change-request: '{

                     "setCloseCode": "true",
                     "attributes": {
                          "short_description": "Automated Software Deployment",
                          "chg_model":"adffaa9e4370211072b7f6be5bb8f2ed",
                          "description": "Automated Software Deployment.",
                          "assignment_group": "a715cd759f2002002920bde8132e7018",
                          "implementation_plan": "Software update is tested and results can be found in Test Summaries Tab.",
                          "backout_plan": "When software fails in production, the previous software release will be re-deployed.",
                          "test_plan": "Testing if the software was successfully deployed"
                      }
                  }'
                deployment-gate: '{"environment":"prod","jobId":"deploy","jobName":"Deploy"}'
        
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: change
    environment: prod
    steps:
      - name: Run deployment scripts
        run: echo Completed Deployment.
